### ISSUE TITLE
With new steals and can libraries can-connect-feathers is looking for a idProp where there isn't one.

### ISSUE THREAD

**Issue by MarcGodard** [canjs/can-connect-feathers#134] opened 2018-11-09 20:19 UTC
```
Uncaught Error: An idProp was not set in the Model for [object Object]. Things may not work as expected.
    at getIdProp (service.js:15)
    at Behavior.getData (service.js:45)
    at Behavior.behavior.(anonymous function) [as getData] (http://localhost:8080/node_modules/can-connect/data/parse/parse.js:325:32)
    at Behavior.get (constructor.js:183)
    at Behavior.get (store.js:645)
    at Function.eval [as get] (map.js:674)
    at DefineMap.editPageItem (news.js:103)
    at {{scope.top.editPageItem()}} (http://localhost:8080/node_modules/can-stache/expressions/call.js:108:16)
    at Call.value (call.js:120)
    at on:click="scope.top.editPageItem()" (http://localhost:8080/node_modules/can-stache-bindings/can-stache-bindings.js:113:20)
```

**Comment by chasenlehara** [comment] 2018-11-13 23:31
I’m closing this issue because it sounds like a duplicate of https://github.com/canjs/can-connect-feathers/issues/136

@MarcGodard please feel free to re-open it if it’s not a duplicate.

**Closed by chasenlehara** 2018-11-13 23:31 UTC
